app = "cloud-detection"
primary_region = "nrt" # Tokyo region

[build]
  dockerfile = "Dockerfile.fly"

[env]
  MODEL_PATH = "/app/models/best.pt"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "90s"
    interval = "30s"
    method = "GET"
    path = "/health"
    timeout = "15s"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1 